name: Deploy Godot Web to itch.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Godot environment and export
      id: export
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        archive_root_folder: true


    - name: Check archive files
      run: ls -la ${{ steps.export.outputs.archive_directory }}

    - name: Deploy to itch.io
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html5
        ITCH_GAME: microbiologist
        ITCH_USER: awesomejerry
        PACKAGE: ${{ steps.export.outputs.archive_directory }}/Web.zip